name: Deploy a producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test        # espera a que el job 'test' del workflow de tests pase
    steps:
      - name: Deploy en VM forVoz
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: voz.enacif.unam.mx
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/ForVoz
            git pull origin main
            docker compose up -d --build
